# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - wheel_left_joint
    - wheel_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000


controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    joint1:
      p: 300.0
      d: 0.1
      i: 1.0
      i_clamp: 0.2
    joint2:
      p: 300.0
      d: 0.1
      i: 1.0
      i_clamp: 0.2
    joint3:
      p: 300.0
      d: 0.1
      i: 1.0
      i_clamp: 0.2
    joint4:
      p: 300
      d: 0.1
      i: 1.0
      i_clamp: 0.2